An error was caught at: 2023-05-18T15:20:21.005779800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:20:21.065381200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:20:21.068384400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:23:30.386136.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:23:30.449701400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:23:30.451703400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:15.473156.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:15.523202200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:48.632915100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:48.689991600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:33:27.671062.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:88)
	at view.View.simulateDatabaseConnectionError(View.java:110)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:33:27.712101900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:88)
	at view.View.simulateDatabaseConnectionError(View.java:110)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:50:46.328350500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:50:46.375901900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:52:27.128357900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:52:27.175400500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:53:41.388604700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:53:41.434645.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:56:38.378278100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:56:38.428323700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:01:50.140396800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:01:50.182511900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:03:08.032996.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:03:08.079039200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:10:41.387104300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:10:41.430143900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:32.822486400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:32.866526300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:49.807871300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:49.853912900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:25.661079800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:25.706120800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:33.641412200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:33.687962100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:14:49.883614700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:14:49.926865300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:23:46.828825300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:23:46.876868700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:24:57.373300700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:24:57.419341700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:25:16.542352400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:25:16.585392400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:05.308375.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:47)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:05.319888900.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:46)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:17.940297100.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:47)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:17.949306.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:46)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:41:11.700175.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:41:11.744253700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.492370200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.502377700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.539415500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.539415500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.742229300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.752239400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.785777400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.785777400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.399957600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.410970800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.448507.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.448507.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:47:22.112952500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:47:49.512173.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.290277100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.300285700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.338320500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.338320500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.562806400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.572814800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.609357700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.609357700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.174683.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.186036900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.226444500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.226444500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:09:22.483382700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:09:22.497758300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:18.865906700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:18.865906700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.226271900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.239461600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.278139600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.278139600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.772788300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.784316500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.823589800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.824590100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.059735200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.069254600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:90)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.103679600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.104680700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:90)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.873411300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.884422500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.917003.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.917003.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.507891400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.518901900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.552935500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.552935500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.349767100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.360284100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.394314.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.394314.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.629457900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.641469.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.683509.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.684509300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.884960800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.894970300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:123)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.928107800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.928107800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:123)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.136916100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.149431800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.183463200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.183463200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T16:18:18.922768800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:67)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T16:18:18.963449200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:96)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T16:18:19.078785300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:67)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T16:18:19.078785300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:96)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T20:10:19.697724700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T20:10:19.738460500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T20:10:19.812107700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T20:10:19.812107700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T19:07:58.866696400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T19:07:58.879398200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T19:07:58.921300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T19:07:58.921300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T22:58:35.236771.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T22:58:35.248806.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T22:58:35.288804.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T22:58:35.289803900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:01:24.939426400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:01:24.949071500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:01:24.980836700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:01:24.981925500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:19:20.817541700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:19:20.829087800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:19:20.862279300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-30T23:19:20.862279300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:44:54.091684200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:27)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:44:54.106697300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:27)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:44:54.157761700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:28)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:44:54.158763.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:28)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:50:42.808445800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:28)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:50:42.818455.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:28)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:50:42.849997700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:50:42.850999100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:51:07.403806700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:51:07.414818.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:51:07.448908900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-03T13:51:07.448908900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T09:55:01.219247800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T09:55:01.229258200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T09:55:01.273300800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T09:55:01.273300800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:10:35.685457800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:10:35.695486700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:10:35.729516100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:10:35.730517100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:20:01.457209600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:20:01.468219600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:20:01.504799800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:20:01.504799800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:23:45.509227300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:23:45.517234400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:23:45.550770500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T10:23:45.550770500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:25:12.520285500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:25:12.532295400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:25:43.813345100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:25:43.823354300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:26:02.041118300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:26:02.052141800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:26:47.376294800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:26:47.390353700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:32:57.175806600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:32:57.186817100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:32:57.224851300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:32:57.225853400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:33:32.515242.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:33:32.524249100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:33:32.557365800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:33:32.558282.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:04.401349300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:04.411357.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:04.449530900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:04.450532.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:23.562109.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:23.573118900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:23.614158.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:35:23.614158.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:36:03.506603700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:36:03.516614.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:36:03.556667600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T11:36:03.556667600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T12:38:49.474314500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T12:38:49.483415400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T12:38:49.515443700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T12:38:49.516444300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T14:13:10.379613300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T14:13:10.389623100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:17:14.888957900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:17:14.900969500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:17:14.934999800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:17:14.936000500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:21:34.979496800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:21:34.989504800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:21:35.023535500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T16:21:35.024536400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:129)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:03.280904.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:03.291916.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:03.325947400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:03.325947400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:13.889920700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:13.899931100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:13.935964300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:13.935964300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:18.640079300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:18.649596200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:18.683627100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:18.684627800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:23.113098600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:23.123107900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:23.161651100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:21:23.161651100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:39:37.817816400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:39:37.826824300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:39:37.858857600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:39:37.858857600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:43:31.352380600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:43:31.361388300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:43:31.390415.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T17:43:31.391417.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:35:49.914735400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:35:49.924744200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:35:49.964287200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:35:49.964287200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:36:38.339908300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:36:38.348916900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:36:38.384099800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:36:38.384099800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:37:43.483167300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:37:43.492679300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:29)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:37:43.527710600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:74)
	at view.View.purchaseSimulation(View.java:53)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

An error was caught at: 2023-06-05T22:37:43.527710600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:102)
	at view.View.simulateDatabaseConnectionError(View.java:130)
	at view.View.purchaseSimulation(View.java:62)
	at startup.Main.main(Main.java:30)
------------------------------------------------------------------------

