An error was caught at: 2023-05-18T15:20:21.005779800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:20:21.065381200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:20:21.068384400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:23:30.386136.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:23:30.449701400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-18T15:23:30.451703400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:15.473156.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:15.523202200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:48.632915100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T01:55:48.689991600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:97)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:33:27.671062.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:88)
	at view.View.simulateDatabaseConnectionError(View.java:110)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:33:27.712101900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:88)
	at view.View.simulateDatabaseConnectionError(View.java:110)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:50:46.328350500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:50:46.375901900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:52:27.128357900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:52:27.175400500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:53:41.388604700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:53:41.434645.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:56:38.378278100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T10:56:38.428323700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:113)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:01:50.140396800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:01:50.182511900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:03:08.032996.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:03:08.079039200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:112)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:10:41.387104300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:10:41.430143900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:32.822486400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:32.866526300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:49.807871300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:11:49.853912900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:25.661079800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:25.706120800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:33.641412200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:13:33.687962100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:14:49.883614700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:14:49.926865300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:23:46.828825300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:23:46.876868700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:24:57.373300700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:24:57.419341700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:25:16.542352400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:25:16.585392400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:85)
	at view.View.simulateDatabaseConnectionError(View.java:114)
	at view.View.purchaseSimulation(View.java:51)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:05.308375.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:47)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:05.319888900.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:46)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:17.940297100.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:47)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:36:17.949306.
Error message: A new purchase is being initiated before the current one is done
java.lang.IllegalStateException: A new purchase is being initiated before the current one is done
	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:46)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:41:11.700175.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:41:11.744253700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:89)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.492370200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.502377700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.539415500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:10.539415500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.742229300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.752239400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.785777400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:45:39.785777400.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.399957600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.410970800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.448507.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:46:43.448507.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:47:22.112952500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T11:47:49.512173.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.290277100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.300285700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.338320500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:16.338320500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.562806400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.572814800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.609357700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:48)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T12:03:32.609357700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:120)
	at view.View.purchaseSimulation(View.java:58)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.174683.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.186036900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.226444500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T22:57:52.226444500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:09:22.483382700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:09:22.497758300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:18.865906700.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:18.865906700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.226271900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.239461600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.278139600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:14:20.278139600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.772788300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.784316500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.823589800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:66)
	at view.View.purchaseSimulation(View.java:49)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:26:33.824590100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:91)
	at view.View.simulateDatabaseConnectionError(View.java:121)
	at view.View.purchaseSimulation(View.java:59)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.059735200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.069254600.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:90)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.103679600.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-19T23:59:04.104680700.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:56)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:38)
	at controller.Controller.enterItemInfo(Controller.java:90)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.873411300.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.884422500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.917003.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:20:23.917003.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.507891400.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.518901900.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.552935500.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:23:12.552935500.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.349767100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.360284100.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.394314.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:24:36.394314.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.629457900.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.641469.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.683509.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:48:27.684509300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:122)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.884960800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.894970300.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:123)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.928107800.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:49:38.928107800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:123)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.136916100.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.149431800.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.183463200.
Error message: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

java.lang.IllegalStateException: An instance of the class Purchase or Payment was re-initiated before the current sale was finished

	at controller.Controller.startSale(Controller.java:65)
	at view.View.purchaseSimulation(View.java:50)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

An error was caught at: 2023-05-22T00:50:46.183463200.
Error message: External Inventory is not reached
integration.FailedToConnectToDatabaseException: External Inventory is not reached
	at integration.inventory.InventoryHandler.connectToExternalInventory(InventoryHandler.java:59)
	at integration.inventory.InventoryHandler.fetchItemFromInventory(InventoryHandler.java:41)
	at controller.Controller.enterItemInfo(Controller.java:92)
	at view.View.simulateDatabaseConnectionError(View.java:125)
	at view.View.purchaseSimulation(View.java:60)
	at startup.Main.main(Main.java:19)
------------------------------------------------------------------------

